include: .included.yml

variables:
    GIT_DEPTH: 1
    nixpkgs_ver: "19.09"
    uploadPath: ./nixos-$CI_JOB_NAME-$CI_PIPELINE_ID

# job names are sorted alphabetically

azure:
    variables:
        formats: azure
    extends:
        - .template

# doesn't build
.cloudstack:
    variables:
        formats: cloudstack
    extends:
        - .template

do:
    variables:
        nixpkgs_ver: unstable
        formats: do
    extends:
        - .template

gce:
    variables:
        formats: gce
    extends:
        - .template

install-iso:
    variables:
        formats: install-iso
    extends:
        - .template

install-iso-hyperv:
    variables:
        formats: install-iso-hyperv
    extends:
        - .template

iso:
    variables:
        formats: iso
    extends:
        - .template

kexec:
    variables:
        formats: kexec
    extends:
        - .template

kexec-bundle:
    variables:
        formats: kexec-bundle
    extends:
        - .template

lxc:
    variables:
        formats: lxc
    extends:
        - .template

lxc-metadata:
    variables:
        formats: lxc-metadata
    extends:
        - .template

openstack:
    variables:
        formats: openstack
    extends:
        - .template

qcow:
    variables:
        formats: qcow
    extends:
        - .template

raw:
    variables:
        formats: raw
    extends:
        - .template

# todo
.sd-aarch64:
    variables:
        formats: sd-aarch64
    script:
        - nix-shell --command './nixos-generate -f $formats --nixpkgs_ver $nixpkgs_ver --system aarch64-linux'
    extends:
        - .template

# todo
.sd-aarch64-installer:
    variables:
        formats: sd-aarch64-installer
    script:
        - nix-shell --command './nixos-generate -f $formats --nixpkgs_ver $nixpkgs_ver --system aarch64-linux'
    extends:
        - .template

virtualbox:
    variables:
        formats: virtualbox
    extends:
        - .template

vm:
    variables:
        formats: vm
    extends:
        - .template
        - .tar_option

vm-nogui:
    variables:
        formats: vm-nogui
    extends:
        - .template
        - .tar_option

